# Default values for go-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: bhaghireddy/go-k8s
  tag: 0.1.0
  pullPolicy: IfNotPresent

service:
  name: go-app
  type: LoadBalancer
  externalPort: 3000
  internalPort: 3000

resources:
  limits:
    cpu: 100m
    memory: 130Mi
  requests:
    cpu: 100m
    memory: 130Mi


